[project]
name = "tt-llm-lab"
version = "0.1.0"
description = "Python uv starter for trying LLM APIs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.33.0",
    "python-dotenv>=1.2.2",
    "beautifulsoup4>=4.14.2",
    "gradio>=6.14.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.7",
]
